### ISSUE TITLE
How could we train the model?

### ISSUE THREAD

**Issue by ZhangYuef** [jiaxiaojunQAQ/Comdefend#6]
It seems there's only test part of the code. So how could we train the model by ourselves?

**Comment by jiaxiaojunQAQ** [comment]
> It seems there's only test part of the code. So how could we train the model by ourselves?

I will release the training code as soon as possible

**Comment by jiaxiaojunQAQ** [comment]
> It seems there's only test part of the code. So how could we train the model by ourselves?

The training code has not been sorted out. If you need it urgently, I can send you the most original one.

**Comment by ZhangYuef** [comment]
> > It seems there's only test part of the code. So how could we train the model by ourselves?
> 
> The training code has not been sorted out. If you need it urgently, I can send you the most original one.

Thanks a lot! I just emailed you

**Comment by the-butterfly** [comment]
One more email, please. For I can't achieve your result from this version and the paper. I want to know what I missed. @jiaxiaojunQAQ

**Comment by jiaxiaojunQAQ** [comment]
> One more email, please. For I can't achieve your result from this version and the paper. I want to know what I missed. @jiaxiaojunQAQ

Which attack method are you defending?

**Comment by jiaxiaojunQAQ** [comment]
which attack method are you defending


发自我的iPhone

------------------ Original ------------------

**Comment by the-butterfly** [comment]
emmm.... The Reconstruction model seems not work at all in my experiment! Fails to recover original image.

**Comment by jiaxiaojunQAQ** [comment]
> emmm.... The Reconstruction model seems not work at all in my experiment! Fails to recover original image.

emmmm.... Are you are from China? If yes, I will help you via WeChat. If not, let me know what the reconstructed image is like

**Comment by the-butterfly** [comment]
Simon_Darren577215 thx!
