### ISSUE TITLE
请问你们在cifar数据集下，ψ=20，λ=0.0001的情况下，最后的loss值收敛到多小？

### ISSUE THREAD

**Issue by hcguoO0** [jiaxiaojunQAQ/Comdefend#7]

**Comment by jiaxiaojunQAQ** [comment]
不记得了，反正最后在test数据集上面测得的PSNR值是32左右

**Comment by hcguoO0** [comment]
顺便再问一下，你们keras版本的代码重构好了吗？，自己写的总是有很多问题

**Comment by hcguoO0** [comment]
又或者你们训练模型的文件可以给我参考一下吗

**Comment by jiaxiaojunQAQ** [comment]
> 顺便再问一下，你们keras版本的代码重构好了吗？，自己写的总是有很多问题

没有，最近在忙ijcai那个对抗样本的比赛，排名还比较靠前，估计得参加完复赛之后才来重构

**Comment by jiaxiaojunQAQ** [comment]
> 又或者你们训练模型的文件可以给我参考一下吗

你可以邮件我，然后我发你一个最原始的版本

**Comment by hcguoO0** [comment]
好的，谢谢
